name: Dynamicyogafrance
favicon: null
layout_spectrum: 0.7566
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2b181'
    - '#ba8887'
    - '#b85957'
    - '#3c2f07'
    - '#5a9370'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
