name: Dynamicyogafr
favicon: null
layout_spectrum: 0.36958
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fa1414'
    - '#0605e7'
    - '#06e8a9'
    - '#e8e504'
    - '#ffffff'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
