name: Dynamicyogafr
favicon: null
layout_spectrum: 0.21367
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7dae45'
    - '#000000'
    - '#375718'
    - '#c45e2e'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
