name: Dynamicyogafr
favicon: null
layout_spectrum: 0.48219
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffa914'
    - '#1e0904'
    - '#b07660'
    - '#cd3c06'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
