name: Dynamicyogafr
favicon: null
layout_spectrum: 0.48219
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f5f5f5'
    - '#770700'
    - '#414015'
    - '#bd771a'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
