name: Dynamicyogafr
favicon: null
layout_spectrum: 0.4189
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c52106'
    - '#180400'
    - '#a9be01'
    - '#1e939a'
    - '#f5f6f8'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
