name: Dynamicyogafr
favicon: null
layout_spectrum: 0.48219
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e130f'
    - '#acc59e'
    - '#556c5c'
    - '#e62a2b'
    - '#ff6870'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
