name: Dynamicyogafr
favicon: null
layout_spectrum: 0.2887998470105231
typography_spectrum: 0.055538809625431895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5625
  lightness: 0.07780131022445858
  saturation: 0.6449081420432776
  rhythmicContrast: 0.23299607750959694
purpose: []
