typography_spectrum: 0.9833869228605181
color:
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
  brandStrength: 0.4796878411434591
  lightness: 0.8160836931783706
  saturation: 0.884104500990361
  rhythmicContrast: 0.44363374658860266
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2943401802331209
analytics:
  google: null
  facebook: null
  twitter: null
name: Dynamicyogafrance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Red Earth Centre
    url: 'http://www.redearthcentre.com'
    type: external
  - name: About
    id: 61b4e90c-5ae8-4084-9c6d-f5d366620dce
    type: content
  - name: Dynamic Yoga Training Method
    url: 'http://dynamicyoga.com'
    type: external
  - name: 'About Dynamic Yoga '
    id: 7924b56d-60ad-48d2-8946-16de67c1e3ca
    type: content
favicon: null
title: Dynamic Yoga France
purpose: []
