name: Dynamicyogafr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11201b'
    - '#ffffff'
    - '#ffb2c8'
    - '#586460'
    - '#8f060d'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
