name: Dynamicyogafr
favicon: null
layout_spectrum: 0.48219
typography_spectrum: 0.30027
title: Dynamic Yoga France
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bbbbbb'
    - '#894d35'
    - '#7f0b1a'
    - '#b38662'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
